// Built-in price estimates: typical US supermarket prices (2026, before sales and
// store brands). Shown in the app as "estimate"; any price you enter wins.
//
// E(name, price, per, options)
//   per   what the price buys: 'lb', 'each', 'dozen', '16 oz', '32 fl oz', 'can', 'bunch'…
//   a     aliases, '|' separated (matched after the same clean-up as recipe text)
//   g     grams in one item ("2 onions", "3 eggs")
//   c     grams in one cup (density, for "1 cup flour" or "2 tbsp oil")
//   w     grams in one of the price's own unit when it isn't a weight/volume (can, bunch, jar…)
//   sz    grams in other named units: { clove: 5, slice: 28 }
//   x     not food (no nutrition)
const E = (n, p, per, o = {}) => {
  const m = String(per).match(/^([\d.]+)\s+(.+)$/);
  return { n, p, q: m ? +m[1] : 1, u: m ? m[2] : per, ...o };
};

export const PRICE_DB = [
  /* ---------- Produce ---------- */
  E('yellow onion', 1.29, 'lb', { a: 'onion|white onion|sweet onion|spanish onion|vidalia onion|brown onion', g: 225, c: 160 }),
  E('red onion', 1.69, 'lb', { a: 'purple onion', g: 225, c: 160 }),
  E('shallot', 4.99, 'lb', { g: 40, c: 160 }),
  E('garlic', 0.6, 'head', { a: 'garlic head|garlic bulb', w: 50, g: 50, c: 136, sz: { clove: 5 } }),
  E('ginger', 4.99, 'lb', { a: 'ginger root|fresh ginger|gingerroot', g: 30, c: 96, sz: { inch: 15, knob: 30 } }),
  E('russet potato', 1.09, 'lb', { a: 'potato|baking potato|idaho potato|white potato', g: 300, c: 150 }),
  E('yukon gold potato', 1.49, 'lb', { a: 'gold potato|yellow potato', g: 170, c: 150 }),
  E('red potato', 1.49, 'lb', { a: 'new potato', g: 170, c: 150 }),
  E('baby potato', 2.99, 'lb', { a: 'fingerling potato|little potato|petite potato', g: 40, c: 150 }),
  E('sweet potato', 1.39, 'lb', { a: 'yam', g: 200, c: 133 }),
  E('carrot', 1.19, 'lb', { a: 'carrots', g: 60, c: 128 }),
  E('baby carrot', 1.79, 'lb', { g: 10, c: 128 }),
  E('celery', 1.99, 'bunch', { a: 'celery rib|celery heart', w: 450, g: 40, c: 101, sz: { stalk: 40, rib: 40 } }),
  E('bell pepper', 1.29, 'each', { a: 'sweet pepper|yellow bell pepper|orange bell pepper|pepper strip', g: 150, c: 149 }),
  E('red bell pepper', 1.59, 'each', { a: 'red pepper', g: 150, c: 149 }),
  E('green bell pepper', 0.99, 'each', { a: 'green pepper', g: 150, c: 149 }),
  E('jalapeno', 2.49, 'lb', { a: 'jalapeño|jalapeno pepper|jalapeño pepper', g: 14, c: 90 }),
  E('poblano pepper', 2.99, 'lb', { a: 'poblano', g: 120, c: 90 }),
  E('serrano pepper', 2.99, 'lb', { a: 'serrano|thai chili|bird eye chili|red chili|green chili', g: 6, c: 90 }),
  E('habanero pepper', 3.99, 'lb', { a: 'habanero|scotch bonnet', g: 8, c: 90 }),
  E('cucumber', 0.89, 'each', { a: 'slicing cucumber', g: 300, c: 119 }),
  E('english cucumber', 1.49, 'each', { a: 'seedless cucumber|hothouse cucumber|persian cucumber|mini cucumber', g: 400, c: 119 }),
  E('zucchini', 1.79, 'lb', { a: 'courgette|green zucchini', g: 200, c: 124 }),
  E('yellow squash', 1.79, 'lb', { a: 'summer squash', g: 200, c: 124 }),
  E('butternut squash', 1.49, 'lb', { g: 1000, c: 140 }),
  E('spaghetti squash', 1.49, 'lb', { g: 1100, c: 101 }),
  E('acorn squash', 1.49, 'lb', { g: 600, c: 140 }),
  E('broccoli', 2.49, 'lb', { a: 'broccoli floret|broccoli crown|broccoli head', g: 300, c: 91, sz: { head: 300 } }),
  E('cauliflower', 3.49, 'head', { a: 'cauliflower floret|cauliflower head', w: 600, g: 600, c: 107 }),
  E('green cabbage', 0.99, 'lb', { a: 'cabbage|savoy cabbage|napa cabbage', g: 900, c: 89, sz: { head: 900 } }),
  E('red cabbage', 1.29, 'lb', { a: 'purple cabbage', g: 900, c: 89, sz: { head: 900 } }),
  E('coleslaw mix', 2.49, '14 oz', { a: 'slaw mix|shredded cabbage|broccoli slaw|coleslaw', c: 70 }),
  E('brussels sprout', 3.49, 'lb', { a: 'brussel sprout|brussels', g: 20, c: 88 }),
  E('asparagus', 3.99, 'lb', { a: 'asparagus spear', g: 20, c: 134, sz: { bunch: 450, spear: 20 } }),
  E('green bean', 2.49, 'lb', { a: 'string bean|haricot vert|snap bean', g: 5, c: 110 }),
  E('snap pea', 3.99, 'lb', { a: 'sugar snap pea|snow pea|pea pod', g: 4, c: 98 }),
  E('corn on the cob', 0.6, 'each', { a: 'corn|sweet corn|ear of corn|corn cob|fresh corn', g: 100, c: 145, sz: { ear: 100 } }),
  E('mushroom', 2.99, '8 oz', { a: 'white mushroom|button mushroom|cremini mushroom|cremini|baby bella|baby bella mushroom|crimini mushroom|sliced mushroom', g: 18, c: 70 }),
  E('portobello mushroom', 1.5, 'each', { a: 'portobello|portabella|portabella mushroom', g: 85, c: 86 }),
  E('shiitake mushroom', 4.99, '4 oz', { a: 'shiitake|oyster mushroom|mixed mushroom', g: 15, c: 70 }),
  E('baby spinach', 3.49, '5 oz', { a: 'spinach|fresh spinach|spinach leaf', c: 30 }),
  E('kale', 2.49, 'bunch', { a: 'lacinato kale|tuscan kale|curly kale|dinosaur kale|baby kale', w: 200, c: 67 }),
  E('collard greens', 1.99, 'bunch', { a: 'collard|collards|collard green|mustard greens', w: 340, c: 36 }),
  E('swiss chard', 2.49, 'bunch', { a: 'chard|rainbow chard', w: 300, c: 36 }),
  E('romaine lettuce', 1.99, 'head', { a: 'romaine|romaine heart|cos lettuce', w: 450, g: 280, c: 47 }),
  E('iceberg lettuce', 1.79, 'head', { a: 'iceberg', w: 750, g: 750, c: 72 }),
  E('lettuce', 1.99, 'head', { a: 'butter lettuce|bibb lettuce|green leaf lettuce|red leaf lettuce|boston lettuce|lettuce leaf', w: 500, g: 500, c: 47, sz: { leaf: 10 } }),
  E('spring mix', 3.99, '5 oz', { a: 'mixed greens|salad greens|salad mix|mesclun|baby greens|greens', c: 30 }),
  E('arugula', 3.99, '5 oz', { a: 'rocket|baby arugula', c: 20 }),
  E('tomato', 1.99, 'lb', { a: 'vine tomato|beefsteak tomato|heirloom tomato|tomatoes on the vine', g: 150, c: 180 }),
  E('roma tomato', 1.49, 'lb', { a: 'plum tomato', g: 100, c: 180 }),
  E('cherry tomato', 3.49, 'pint', { a: 'grape tomato|pint tomato', g: 17, c: 149 }),
  E('tomatillo', 2.49, 'lb', { g: 34, c: 132 }),
  E('avocado', 1.25, 'each', { a: 'hass avocado', g: 150, c: 150 }),
  E('lemon', 0.69, 'each', { a: 'lemon zest|meyer lemon|lemon wedge', g: 100, c: 212 }),
  E('lime', 0.4, 'each', { a: 'lime zest|lime wedge|key lime', g: 67, c: 212 }),
  E('orange', 0.99, 'each', { a: 'navel orange|orange zest|mandarin|clementine|tangerine|cara cara orange', g: 180, c: 180 }),
  E('grapefruit', 1.29, 'each', { g: 250, c: 230 }),
  E('apple', 1.79, 'lb', { a: 'granny smith apple|honeycrisp apple|gala apple|fuji apple|red apple|green apple', g: 200, c: 125 }),
  E('banana', 0.62, 'lb', { a: 'ripe banana', g: 118, c: 150 }),
  E('strawberry', 3.49, 'lb', { a: 'strawberries|fresh strawberry', g: 12, c: 152 }),
  E('blueberry', 3.99, '11 oz', { a: 'blueberries|fresh blueberry', c: 148 }),
  E('raspberry', 3.99, '6 oz', { a: 'raspberries', c: 123 }),
  E('blackberry', 3.49, '6 oz', { a: 'blackberries', c: 144 }),
  E('berry', 3.99, '11 oz', { a: 'berries|mixed berry|fresh berry', c: 145 }),
  E('grape', 2.99, 'lb', { a: 'red grape|green grape|seedless grape', g: 5, c: 151 }),
  E('cherry', 4.99, 'lb', { a: 'cherries|sweet cherry', g: 8, c: 138 }),
  E('pineapple', 2.99, 'each', { a: 'fresh pineapple|pineapple chunk', g: 900, c: 165 }),
  E('mango', 1.25, 'each', { a: 'fresh mango', g: 200, c: 165 }),
  E('peach', 1.99, 'lb', { a: 'nectarine', g: 150, c: 154 }),
  E('pear', 1.79, 'lb', { a: 'bartlett pear|bosc pear|anjou pear', g: 180, c: 140 }),
  E('kiwi', 0.5, 'each', { a: 'kiwifruit|kiwi fruit', g: 75, c: 180 }),
  E('watermelon', 5.99, 'each', { g: 4500, c: 152 }),
  E('cantaloupe', 2.99, 'each', { a: 'melon|honeydew', g: 1200, c: 160 }),
  E('pomegranate', 2.49, 'each', { a: 'pomegranate seed|pomegranate aril', g: 280, c: 174 }),
  E('plantain', 0.69, 'each', { g: 220, c: 150 }),
  E('cilantro', 0.99, 'bunch', { a: 'fresh cilantro|coriander leaf|cilantro leaf|fresh coriander', w: 60, c: 16, sz: { sprig: 1, handful: 10 } }),
  E('parsley', 0.99, 'bunch', { a: 'flat leaf parsley|italian parsley|curly parsley|fresh parsley|parsley leaf', w: 60, c: 60, sz: { sprig: 1, handful: 10 } }),
  E('basil', 2.49, '0.75 oz', { a: 'fresh basil|basil leaf|thai basil|sweet basil', c: 24, sz: { sprig: 2, leaf: 0.5, handful: 10, bunch: 21 } }),
  E('mint', 2.49, '0.75 oz', { a: 'fresh mint|mint leaf|spearmint', c: 20, sz: { sprig: 1, leaf: 0.2, bunch: 21 } }),
  E('dill', 2.49, '0.75 oz', { a: 'fresh dill|dill weed|dill sprig', c: 9, sz: { sprig: 1, bunch: 21 } }),
  E('rosemary', 2.49, '0.75 oz', { a: 'fresh rosemary|rosemary sprig', c: 30, sz: { sprig: 1, bunch: 21 } }),
  E('fresh thyme', 2.49, '0.75 oz', { a: 'thyme sprig|fresh thyme leaf', c: 30, sz: { sprig: 0.5, bunch: 21 } }),
  E('sage', 2.49, '0.75 oz', { a: 'fresh sage|sage leaf', c: 20, sz: { leaf: 0.7, sprig: 2, bunch: 21 } }),
  E('chive', 2.49, '0.75 oz', { a: 'chives|fresh chive', c: 48, sz: { bunch: 21 } }),
  E('scallion', 0.99, 'bunch', { a: 'green onion|spring onion|scallions', w: 100, g: 15, c: 100 }),
  E('leek', 1.99, 'each', { g: 90, c: 89 }),
  E('radish', 1.49, 'bunch', { a: 'radishes|red radish', w: 250, g: 10, c: 116 }),
  E('beet', 2.49, 'lb', { a: 'beets|beetroot|red beet', g: 130, c: 136 }),
  E('parsnip', 2.49, 'lb', { g: 100, c: 133 }),
  E('turnip', 1.49, 'lb', { a: 'rutabaga', g: 120, c: 130 }),
  E('eggplant', 1.99, 'lb', { a: 'aubergine|japanese eggplant', g: 450, c: 82 }),
  E('bok choy', 2.49, 'lb', { a: 'baby bok choy|pak choi|bok choi', g: 100, c: 70 }),
  E('fennel', 2.49, 'each', { a: 'fennel bulb', g: 230, c: 87 }),
  E('okra', 3.99, 'lb', { g: 12, c: 100 }),
  E('bean sprout', 1.99, '10 oz', { a: 'mung bean sprout|sprouts', c: 104 }),
  E('date', 5.99, '8 oz', { a: 'medjool date|dates|pitted date', g: 24, c: 147 }),

  /* ---------- Frozen ---------- */
  E('frozen pea', 1.79, '16 oz', { a: 'peas|green pea|pea|frozen green pea|sweet pea', c: 134 }),
  E('frozen corn', 1.79, '16 oz', { a: 'corn kernel|frozen corn kernel|frozen sweet corn', c: 145 }),
  E('frozen broccoli', 1.99, '12 oz', { a: 'frozen broccoli floret', c: 91 }),
  E('frozen mixed vegetable', 1.79, '16 oz', { a: 'mixed vegetable|frozen vegetable|stir fry vegetable|frozen stir fry vegetable', c: 130 }),
  E('frozen spinach', 1.99, '10 oz', { a: 'chopped frozen spinach', c: 190 }),
  E('edamame', 2.99, '12 oz', { a: 'shelled edamame|frozen edamame', c: 155 }),
  E('frozen berry', 4.49, '16 oz', { a: 'frozen mixed berry|frozen fruit|frozen blueberry|frozen strawberry', c: 140 }),
  E('frozen mango', 3.99, '16 oz', { a: 'mango chunk|frozen mango chunk', c: 165 }),
  E('cauliflower rice', 2.99, '12 oz', { a: 'riced cauliflower|frozen cauliflower rice', c: 107 }),
  E('hash brown', 2.99, '30 oz', { a: 'frozen hash brown|shredded hash brown|hashbrown', c: 156 }),
  E('french fry', 3.49, '32 oz', { a: 'fries|frozen fries|frozen french fry|tater tot', c: 90 }),
  E('potsticker', 5.99, '24 oz', { a: 'gyoza|dumpling|frozen dumpling|frozen potsticker', g: 25 }),
  E('puff pastry', 5.49, '17.3 oz', { a: 'puff pastry sheet', sz: { sheet: 245 } }),
  E('pie crust', 3.49, '2 each', { a: 'refrigerated pie crust|frozen pie crust|pie shell|pie dough', g: 225 }),
  E('ice cream', 4.99, '48 fl oz', { a: 'vanilla ice cream', c: 132 }),

  /* ---------- Meat & seafood ---------- */
  E('chicken breast', 3.99, 'lb', { a: 'chicken|chicken breasts|boneless chicken breast|chicken tender|chicken tenderloin|chicken cutlet|chicken meat', g: 200, c: 140 }),
  E('chicken thigh', 2.99, 'lb', { a: 'boneless chicken thigh|chicken thigh fillet|boneless skinless chicken thigh', g: 110, c: 140 }),
  E('bone in chicken thigh', 1.99, 'lb', { a: 'bone in skin on chicken thigh|skin on chicken thigh', g: 170 }),
  E('chicken drumstick', 1.69, 'lb', { a: 'drumstick|chicken leg', g: 110 }),
  E('chicken wing', 3.49, 'lb', { a: 'wing|wings|chicken wingette', g: 32 }),
  E('whole chicken', 1.79, 'lb', { a: 'roasting chicken|fryer chicken', g: 1800 }),
  E('rotisserie chicken', 7.99, 'each', { a: 'cooked chicken|shredded chicken|shredded rotisserie chicken|leftover chicken', g: 650, c: 140 }),
  E('ground chicken', 4.99, 'lb', { c: 225 }),
  E('ground turkey', 4.49, 'lb', { a: 'lean ground turkey|turkey mince', c: 225 }),
  E('ground beef', 5.49, 'lb', { a: 'lean ground beef|hamburger|beef mince|minced beef|ground chuck|ground sirloin|80/20 ground beef|90/10 ground beef', c: 225 }),
  E('beef stew meat', 6.99, 'lb', { a: 'stew meat|stewing beef|beef chuck|beef cube', c: 150 }),
  E('chuck roast', 6.99, 'lb', { a: 'beef chuck roast|pot roast|beef roast', g: 1300 }),
  E('beef brisket', 6.99, 'lb', { a: 'brisket' }),
  E('flank steak', 9.99, 'lb', { a: 'skirt steak|flat iron steak|hanger steak', g: 680 }),
  E('sirloin steak', 9.99, 'lb', { a: 'steak|top sirloin|sirloin|new york strip|strip steak|beef steak', g: 280 }),
  E('ribeye steak', 14.99, 'lb', { a: 'ribeye|rib eye|rib eye steak', g: 340 }),
  E('short rib', 9.99, 'lb', { a: 'beef short rib|short ribs', g: 200 }),
  E('ground pork', 3.99, 'lb', { a: 'pork mince', c: 225 }),
  E('pork chop', 3.99, 'lb', { a: 'boneless pork chop|pork loin chop|center cut pork chop', g: 200 }),
  E('pork tenderloin', 4.49, 'lb', { g: 500 }),
  E('pork shoulder', 2.49, 'lb', { a: 'pork butt|boston butt|pork roast|pork loin', g: 1800 }),
  E('pork ribs', 4.99, 'lb', { a: 'baby back rib|spare rib|ribs|pork rib' }),
  E('bacon', 6.49, '16 oz', { a: 'thick cut bacon|bacon strip|bacon slice|streaky bacon|pancetta', g: 20, c: 150, sz: { slice: 20, strip: 20, rasher: 20 } }),
  E('turkey bacon', 4.49, '12 oz', { g: 14, sz: { slice: 14, strip: 14 } }),
  E('breakfast sausage', 4.49, '16 oz', { a: 'pork sausage|sausage patty|sausage link|breakfast sausage link|ground sausage', g: 40, c: 225 }),
  E('italian sausage', 4.99, '1.25 lb', { a: 'sausage|sweet italian sausage|hot italian sausage|mild italian sausage|italian sausage link', g: 110, c: 225, sz: { link: 110 } }),
  E('smoked sausage', 3.99, '14 oz', { a: 'kielbasa|andouille|andouille sausage|polish sausage', g: 400, c: 140 }),
  E('chicken sausage', 5.49, '12 oz', { a: 'chicken apple sausage', g: 85, sz: { link: 85 } }),
  E('chorizo', 3.99, '10 oz', { a: 'mexican chorizo|spanish chorizo', c: 225 }),
  E('ham', 5.99, '9 oz', { a: 'deli ham|sliced ham|diced ham|ham steak|cooked ham', g: 28, c: 140, sz: { slice: 28 } }),
  E('deli turkey', 5.99, '9 oz', { a: 'sliced turkey|turkey deli meat|turkey breast|smoked turkey|roast turkey', g: 28, sz: { slice: 28 } }),
  E('hot dog', 4.49, '16 oz', { a: 'frank|frankfurter|hot dogs|beef hot dog', g: 45 }),
  E('pepperoni', 3.49, '6 oz', { a: 'sliced pepperoni', g: 2, sz: { slice: 2 } }),
  E('salami', 4.99, '8 oz', { a: 'genoa salami|soppressata', sz: { slice: 8 } }),
  E('prosciutto', 5.99, '3 oz', { sz: { slice: 15 } }),
  E('meatball', 6.99, '26 oz', { a: 'frozen meatball|meatballs', g: 28 }),
  E('ground lamb', 8.99, 'lb', { a: 'lamb|lamb shoulder|lamb stew meat', c: 225 }),
  E('lamb chop', 14.99, 'lb', { a: 'lamb chops|rack of lamb', g: 100 }),
  E('salmon', 10.99, 'lb', { a: 'salmon fillet|atlantic salmon|salmon filet|sockeye salmon|salmon steak', g: 170, sz: { fillet: 170 } }),
  E('smoked salmon', 6.99, '4 oz', { a: 'lox|nova lox' }),
  E('shrimp', 8.99, 'lb', { a: 'large shrimp|raw shrimp|peeled shrimp|jumbo shrimp|frozen shrimp|prawn|cooked shrimp', g: 15, c: 145 }),
  E('cod', 9.99, 'lb', { a: 'cod fillet|white fish|whitefish|haddock|pollock|halibut|white fish fillet|fish fillet', g: 170, sz: { fillet: 170 } }),
  E('tilapia', 6.99, 'lb', { a: 'tilapia fillet|catfish|swai', g: 115, sz: { fillet: 115 } }),
  E('tuna steak', 12.99, 'lb', { a: 'ahi tuna|ahi|sushi grade tuna|swordfish', g: 170 }),
  E('scallop', 19.99, 'lb', { a: 'sea scallop|bay scallop', g: 30 }),
  E('mussel', 5.99, 'lb', { a: 'mussels|clam|clams' }),
  E('crab meat', 9.99, '8 oz', { a: 'lump crab meat|crab|imitation crab', c: 135 }),
  E('canned tuna', 1.29, 'can', { a: 'tuna|tuna fish|chunk light tuna|albacore tuna|solid white tuna|tuna in water', w: 142, c: 150 }),
  E('sardine', 1.99, 'can', { a: 'sardines|canned sardine', w: 125 }),
  E('anchovy', 2.99, 'can', { a: 'anchovy fillet|anchovies', w: 56, g: 4, sz: { fillet: 4 } }),
  E('tofu', 2.49, '14 oz', { a: 'firm tofu|extra firm tofu|silken tofu|soft tofu|block tofu', g: 397, c: 250, sz: { block: 397, package: 397 } }),
  E('tempeh', 3.99, '8 oz', { g: 227, c: 166 }),

  /* ---------- Dairy & eggs ---------- */
  E('egg', 3.99, 'dozen', { a: 'eggs|large egg|whole egg|egg yolk|egg white|hard boiled egg|hard-boiled egg', g: 50, c: 243 }),
  E('milk', 3.79, 'gallon', { a: 'whole milk|2% milk|skim milk|1% milk|low fat milk|reduced fat milk|nonfat milk|dairy milk', c: 245 }),
  E('buttermilk', 2.49, 'quart', { c: 245 }),
  E('half and half', 2.49, 'pint', { a: 'half & half|half-and-half', c: 242 }),
  E('heavy cream', 3.99, 'pint', { a: 'heavy whipping cream|whipping cream|double cream|cream', c: 238 }),
  E('sour cream', 2.29, '16 oz', { a: 'light sour cream|creme fraiche|crème fraîche', c: 230 }),
  E('butter', 4.99, 'lb', { a: 'unsalted butter|salted butter|stick butter|melted butter|softened butter', c: 227, sz: { stick: 113 } }),
  E('ghee', 8.99, '13 oz', { a: 'clarified butter', c: 218 }),
  E('greek yogurt', 5.49, '32 oz', { a: 'plain greek yogurt|nonfat greek yogurt|2% greek yogurt|full fat greek yogurt', c: 245, g: 150 }),
  E('yogurt', 3.49, '32 oz', { a: 'plain yogurt|vanilla yogurt|whole milk yogurt|natural yogurt', c: 245, g: 170 }),
  E('cream cheese', 2.49, '8 oz', { a: 'neufchatel|whipped cream cheese|cream cheese block', c: 232, sz: { block: 227 } }),
  E('cottage cheese', 3.49, '16 oz', { c: 226 }),
  E('ricotta', 3.99, '15 oz', { a: 'ricotta cheese|whole milk ricotta|part skim ricotta', c: 246 }),
  E('mascarpone', 4.99, '8 oz', { c: 230 }),
  E('cheddar', 3.99, '8 oz', { a: 'cheddar cheese|sharp cheddar|shredded cheddar|mild cheddar|shredded cheese|cheese|white cheddar', c: 113, sz: { slice: 21 } }),
  E('mozzarella', 3.99, '8 oz', { a: 'mozzarella cheese|shredded mozzarella|part skim mozzarella|low moisture mozzarella', c: 112, sz: { slice: 21 } }),
  E('fresh mozzarella', 4.99, '8 oz', { a: 'burrata|mozzarella ball|bocconcini|mozzarella pearl', c: 225 }),
  E('parmesan', 5.99, '5 oz', { a: 'parmesan cheese|parmigiano reggiano|grated parmesan|shaved parmesan|parm|pecorino|pecorino romano|grana padano', c: 100 }),
  E('feta', 4.49, '6 oz', { a: 'feta cheese|crumbled feta', c: 150 }),
  E('monterey jack', 3.99, '8 oz', { a: 'pepper jack|mexican cheese blend|shredded mexican cheese|colby jack|monterey jack cheese|mexican blend cheese|taco cheese', c: 113, sz: { slice: 21 } }),
  E('swiss cheese', 4.49, '8 oz', { a: 'swiss', c: 108, sz: { slice: 21 } }),
  E('provolone', 4.49, '8 oz', { a: 'provolone cheese', c: 110, sz: { slice: 21 } }),
  E('american cheese', 3.99, '12 oz', { a: 'american cheese slice|cheese slice|velveeta', sz: { slice: 21 } }),
  E('goat cheese', 4.49, '4 oz', { a: 'chevre|chèvre|crumbled goat cheese', c: 120 }),
  E('blue cheese', 3.99, '4 oz', { a: 'gorgonzola|crumbled blue cheese|bleu cheese', c: 135 }),
  E('gruyere', 7.99, '7 oz', { a: 'gruyère|fontina|emmental', c: 108 }),
  E('gouda', 4.99, '7 oz', { a: 'smoked gouda|havarti', c: 108, sz: { slice: 21 } }),
  E('brie', 6.99, '8 oz', { a: 'camembert' }),
  E('queso fresco', 3.99, '10 oz', { a: 'cotija|cotija cheese|panela', c: 130 }),
  E('paneer', 5.99, '12 oz', { a: 'halloumi', c: 150 }),
  E('string cheese', 4.99, '12 each', { a: 'mozzarella stick|cheese stick', g: 28 }),
  E('oat milk', 3.99, '0.5 gallon', { a: 'oatmilk', c: 240 }),
  E('almond milk', 3.49, '0.5 gallon', { a: 'unsweetened almond milk|soy milk|plant milk|nondairy milk|non-dairy milk', c: 240 }),
  E('coconut milk', 1.99, 'can', { a: 'full fat coconut milk|light coconut milk|canned coconut milk|unsweetened coconut milk', w: 400, c: 226 }),
  E('coconut cream', 2.49, 'can', { w: 400, c: 240 }),
  E('evaporated milk', 1.49, 'can', { w: 354, c: 252 }),
  E('sweetened condensed milk', 2.29, 'can', { a: 'condensed milk', w: 396, c: 306 }),

  /* ---------- Bakery ---------- */
  E('sandwich bread', 2.99, 'loaf', { a: 'bread|white bread|wheat bread|whole wheat bread|multigrain bread|bread slice|toast|texas toast|rye bread', w: 567, g: 28, c: 30, sz: { slice: 28 } }),
  E('sourdough bread', 4.99, 'loaf', { a: 'sourdough|country bread|crusty bread|artisan bread|italian bread|french bread', w: 680, g: 50, c: 40, sz: { slice: 50 } }),
  E('baguette', 2.99, 'each', { a: 'french baguette', g: 250, sz: { slice: 15 } }),
  E('ciabatta', 3.49, 'each', { a: 'ciabatta roll|focaccia|ciabatta bread', g: 280 }),
  E('hamburger bun', 2.49, '8 each', { a: 'burger bun|bun|buns|hot dog bun|sandwich roll|slider bun|kaiser roll|sub roll|hoagie roll', g: 50 }),
  E('brioche bun', 3.99, '6 each', { a: 'brioche|brioche roll|potato bun|pretzel bun', g: 60 }),
  E('dinner roll', 3.49, '12 each', { a: 'roll|rolls|hawaiian roll|slider roll', g: 28 }),
  E('flour tortilla', 2.99, '10 each', { a: 'tortilla|large flour tortilla|burrito tortilla|wrap|whole wheat tortilla|soft taco tortilla', g: 50 }),
  E('corn tortilla', 2.49, '30 each', { a: 'street taco tortilla|white corn tortilla|yellow corn tortilla', g: 26 }),
  E('taco shell', 2.49, '12 each', { a: 'hard taco shell|tostada|tostada shell', g: 11 }),
  E('pita', 2.99, '6 each', { a: 'pita bread|pita pocket|flatbread|lavash', g: 60 }),
  E('naan', 3.49, '2 each', { a: 'naan bread|garlic naan', g: 90 }),
  E('english muffin', 2.99, '6 each', { g: 57 }),
  E('bagel', 3.49, '6 each', { a: 'bagels|everything bagel|plain bagel', g: 100 }),
  E('croissant', 4.99, '6 each', { g: 57 }),
  E('pizza dough', 2.99, 'lb', { a: 'pizza crust|refrigerated pizza dough|naan pizza crust', g: 450 }),
  E('breadcrumb', 2.49, '15 oz', { a: 'bread crumbs|breadcrumbs|italian breadcrumb|seasoned breadcrumb|dry breadcrumb', c: 108 }),
  E('panko', 2.99, '8 oz', { a: 'panko breadcrumb|panko bread crumbs|japanese breadcrumb', c: 60 }),
  E('crouton', 2.49, '5 oz', { a: 'croutons', c: 30 }),

  /* ---------- Pasta & grains ---------- */
  E('pasta', 1.49, 'lb', { a: 'spaghetti|penne|rigatoni|linguine|fettuccine|rotini|fusilli|farfalle|bow tie pasta|ziti|elbow macaroni|macaroni|angel hair|shell pasta|shells|orecchiette|bucatini|pappardelle|campanelle|cavatappi|paccheri|tagliatelle|dry pasta|short pasta|long pasta|whole wheat pasta|penne pasta|spaghetti noodle|pasta shell|medium shell', c: 100, g: 450 }),
  E('egg noodle', 2.49, '12 oz', { a: 'wide egg noodle|extra wide egg noodle', c: 38 }),
  E('lasagna noodle', 2.49, 'lb', { a: 'lasagna sheet|no boil lasagna noodle|oven ready lasagna noodle|lasagna', g: 20, sz: { sheet: 20, noodle: 20 } }),
  E('orzo', 1.99, 'lb', { c: 170 }),
  E('couscous', 2.99, '10 oz', { a: 'pearl couscous|israeli couscous', c: 173 }),
  E('ramen noodle', 0.35, '3 oz', { a: 'instant ramen|ramen|ramen noodle block|instant noodle', g: 85, sz: { package: 85, block: 85 } }),
  E('rice noodle', 2.99, '14 oz', { a: 'pad thai noodle|rice stick|vermicelli|rice vermicelli|glass noodle', c: 60, g: 400 }),
  E('soba noodle', 3.49, '9.5 oz', { a: 'soba|buckwheat noodle', c: 60, g: 270 }),
  E('udon noodle', 2.49, '7 oz', { a: 'udon|lo mein noodle|lo mein|chow mein noodle|yakisoba noodle|chinese egg noodle|noodle|noodles', g: 200, c: 60 }),
  E('gnocchi', 2.99, '16 oz', { a: 'potato gnocchi', c: 150 }),
  E('tortellini', 4.49, '9 oz', { a: 'cheese tortellini|ravioli|cheese ravioli|refrigerated tortellini', c: 110 }),
  E('white rice', 1.29, 'lb', { a: 'rice|long grain rice|long grain white rice|short grain rice|sushi rice|medium grain rice|uncooked rice|instant rice|minute rice', c: 185 }),
  E('jasmine rice', 1.99, 'lb', { a: 'thai jasmine rice', c: 185 }),
  E('basmati rice', 2.29, 'lb', { a: 'basmati', c: 185 }),
  E('brown rice', 1.49, 'lb', { a: 'long grain brown rice|wild rice', c: 190 }),
  E('arborio rice', 2.99, 'lb', { a: 'risotto rice|carnaroli rice', c: 200 }),
  E('cooked rice', 1.29, 'lb', { a: 'leftover rice|day old rice|steamed rice|cooked white rice|cooked brown rice', c: 158 }),
  E('quinoa', 4.99, 'lb', { a: 'white quinoa|red quinoa|tricolor quinoa', c: 170 }),
  E('rolled oats', 3.49, '42 oz', { a: 'oats|old fashioned oats|oatmeal|quick oats|quick cooking oats|steel cut oats|old fashioned rolled oats', c: 81 }),
  E('farro', 3.99, 'lb', { a: 'pearled farro|barley|pearl barley|bulgur|freekeh', c: 190 }),
  E('cornmeal', 2.49, '24 oz', { a: 'polenta|grits|corn grits|yellow cornmeal', c: 157 }),
  E('wonton wrapper', 2.99, '12 oz', { a: 'egg roll wrapper|dumpling wrapper|gyoza wrapper|wonton skin', g: 8, sz: { sheet: 8, wrapper: 8 } }),
  E('rice paper', 3.49, '12 oz', { a: 'rice paper wrapper|spring roll wrapper', g: 8, sz: { sheet: 8, wrapper: 8 } }),

  /* ---------- Canned & jarred ---------- */
  E('black bean', 1.09, 'can', { a: 'black beans|canned black bean', w: 425, c: 172 }),
  E('chickpea', 1.09, 'can', { a: 'chickpeas|garbanzo bean|garbanzo|canned chickpea', w: 425, c: 164 }),
  E('kidney bean', 1.09, 'can', { a: 'red kidney bean|dark red kidney bean', w: 425, c: 172 }),
  E('pinto bean', 1.09, 'can', { a: 'pinto', w: 425, c: 172 }),
  E('cannellini bean', 1.29, 'can', { a: 'white bean|great northern bean|navy bean|butter bean|lima bean|white kidney bean', w: 425, c: 179 }),
  E('bean', 1.09, 'can', { a: 'beans|canned bean|mixed bean|black eyed pea', w: 425, c: 172 }),
  E('refried bean', 1.49, 'can', { a: 'refried beans', w: 454, c: 250 }),
  E('baked bean', 1.79, 'can', { a: 'baked beans|pork and bean', w: 454, c: 254 }),
  E('lentil', 1.99, 'lb', { a: 'lentils|red lentil|green lentil|brown lentil|french lentil|dried lentil|split pea', c: 192 }),
  E('diced tomato', 1.19, 'can', { a: 'canned diced tomato|fire roasted tomato|fire roasted diced tomato|petite diced tomato|canned tomato|diced tomatoes with green chile|rotel', w: 411, c: 240 }),
  E('crushed tomato', 1.79, 'can', { a: 'crushed tomatoes|canned crushed tomato|tomato puree|passata', w: 794, c: 242 }),
  E('whole peeled tomato', 2.49, 'can', { a: 'whole tomato|san marzano tomato|peeled tomato|whole canned tomato', w: 794, c: 240 }),
  E('tomato sauce', 0.89, 'can', { a: 'canned tomato sauce', w: 227, c: 245 }),
  E('tomato paste', 0.89, 'can', { a: 'double concentrated tomato paste', w: 170, c: 262 }),
  E('marinara sauce', 3.49, 'jar', { a: 'marinara|pasta sauce|spaghetti sauce|tomato basil sauce|red sauce|arrabbiata sauce|vodka sauce', w: 680, c: 250 }),
  E('pizza sauce', 1.99, '14 oz', { c: 250 }),
  E('alfredo sauce', 3.49, '15 oz', { a: 'alfredo', c: 250 }),
  E('pesto', 3.99, '6 oz', { a: 'basil pesto|pesto sauce', c: 260 }),
  E('salsa', 3.49, '16 oz', { a: 'jarred salsa|salsa verde|chunky salsa|pico de gallo', c: 260 }),
  E('enchilada sauce', 1.99, '10 oz', { a: 'red enchilada sauce|green enchilada sauce', c: 250 }),
  E('chicken broth', 2.49, '32 fl oz', { a: 'chicken stock|low sodium chicken broth|bone broth|broth|stock|chicken bone broth', c: 240 }),
  E('beef broth', 2.49, '32 fl oz', { a: 'beef stock|low sodium beef broth', c: 240 }),
  E('vegetable broth', 2.49, '32 fl oz', { a: 'vegetable stock|veggie broth|veggie stock|low sodium vegetable broth', c: 240 }),
  E('bouillon', 3.49, '8 oz', { a: 'bouillon cube|chicken bouillon|better than bouillon|stock cube|beef bouillon', c: 200, g: 4, sz: { cube: 4 } }),
  E('canned corn', 0.99, 'can', { a: 'whole kernel corn|creamed corn|cream style corn', w: 432, c: 164 }),
  E('green chile', 1.29, 'can', { a: 'diced green chile|chopped green chile|hatch chile|green chiles', w: 113, c: 140 }),
  E('chipotle pepper in adobo', 2.49, 'can', { a: 'chipotle in adobo|chipotle pepper|chipotle|adobo sauce|chipotles in adobo', w: 198, g: 15, sz: { pepper: 15 } }),
  E('roasted red pepper', 3.49, 'jar', { a: 'jarred roasted red pepper|roasted pepper|pimento|pimiento', w: 340, c: 150 }),
  E('artichoke heart', 3.49, 'can', { a: 'artichoke|marinated artichoke heart|artichokes', w: 396, c: 168 }),
  E('olive', 3.49, '6 oz', { a: 'black olive|kalamata olive|green olive|sliced olive|castelvetrano olive|pitted olive|sliced black olive', g: 4, c: 135 }),
  E('caper', 2.99, '3.5 oz', { a: 'capers|caper berry', c: 136 }),
  E('sun dried tomato', 4.49, '8.5 oz', { a: 'sundried tomato|sun dried tomatoes in oil', c: 55 }),
  E('pickle', 3.49, '24 oz', { a: 'dill pickle|pickle spear|pickle chip|gherkin|cornichon|pickled jalapeno|relish', g: 30, c: 150, sz: { spear: 30 } }),
  E('kimchi', 5.99, '16 oz', { a: 'sauerkraut', c: 150 }),
  E('water chestnut', 1.49, 'can', { a: 'water chestnuts|bamboo shoot', w: 227, c: 150 }),
  E('canned pineapple', 1.79, 'can', { a: 'pineapple tidbit|crushed pineapple|pineapple ring|mandarin orange', w: 567, c: 246 }),
  E('peanut butter', 3.49, '16 oz', { a: 'creamy peanut butter|crunchy peanut butter|natural peanut butter|pb', c: 258 }),
  E('almond butter', 7.99, '12 oz', { a: 'cashew butter|sunflower butter|nut butter', c: 250 }),
  E('jam', 3.49, '18 oz', { a: 'jelly|strawberry jam|raspberry jam|preserves|fruit spread|grape jelly|apricot jam|marmalade', c: 320 }),
  E('hazelnut spread', 4.49, '13 oz', { a: 'nutella|chocolate hazelnut spread', c: 300 }),
  E('pumpkin puree', 2.49, 'can', { a: 'canned pumpkin|pumpkin|pure pumpkin', w: 425, c: 245 }),
  E('applesauce', 2.99, '24 oz', { a: 'apple sauce|unsweetened applesauce', c: 255 }),
  E('cream of mushroom soup', 1.29, 'can', { a: 'cream of chicken soup|condensed soup|cream of celery soup|condensed cream of mushroom soup', w: 298, c: 250 }),

  /* ---------- Baking & spices ---------- */
  E('all purpose flour', 3.49, '5 lb', { a: 'flour|ap flour|plain flour|white flour|unbleached flour|self rising flour', c: 125 }),
  E('whole wheat flour', 4.49, '5 lb', { a: 'wheat flour|white whole wheat flour', c: 120 }),
  E('bread flour', 4.99, '5 lb', { a: 'cake flour|pastry flour|00 flour|semolina', c: 127 }),
  E('almond flour', 7.99, '16 oz', { a: 'almond meal|blanched almond flour|coconut flour', c: 96 }),
  E('sugar', 3.99, '4 lb', { a: 'granulated sugar|white sugar|cane sugar|caster sugar|superfine sugar', c: 200 }),
  E('brown sugar', 2.99, '2 lb', { a: 'light brown sugar|dark brown sugar|packed brown sugar|coconut sugar|turbinado sugar', c: 220 }),
  E('powdered sugar', 2.49, '2 lb', { a: 'confectioners sugar|icing sugar|confectioner sugar', c: 120 }),
  E('baking powder', 2.49, '8.1 oz', { c: 230 }),
  E('baking soda', 1.29, '16 oz', { a: 'bicarbonate of soda|bicarb', c: 220 }),
  E('yeast', 1.79, '0.75 oz', { a: 'active dry yeast|instant yeast|rapid rise yeast|dry yeast', c: 136, sz: { package: 7, envelope: 7 } }),
  E('cornstarch', 2.49, '16 oz', { a: 'corn starch|cornflour|arrowroot|potato starch|tapioca starch', c: 128 }),
  E('cocoa powder', 3.99, '8 oz', { a: 'unsweetened cocoa|unsweetened cocoa powder|dutch process cocoa|cocoa|cacao powder', c: 86 }),
  E('chocolate chip', 3.49, '12 oz', { a: 'semi sweet chocolate chip|semisweet chocolate chip|chocolate chips|mini chocolate chip|dark chocolate chip|white chocolate chip|chocolate chunk', c: 170 }),
  E('dark chocolate', 3.49, '3.5 oz', { a: 'chocolate|bittersweet chocolate|semisweet chocolate|chocolate bar|baking chocolate|milk chocolate', c: 170 }),
  E('vanilla extract', 7.99, '2 fl oz', { a: 'vanilla|pure vanilla extract|vanilla bean paste|almond extract', c: 208 }),
  E('molasses', 4.49, '12 fl oz', { a: 'blackstrap molasses', c: 337 }),
  E('shortening', 4.49, '16 oz', { a: 'vegetable shortening|crisco|lard', c: 205 }),
  E('marshmallow', 1.99, '10 oz', { a: 'marshmallows|mini marshmallow', c: 50 }),
  E('graham cracker', 3.99, '14.4 oz', { a: 'graham cracker crumb|graham crackers', c: 84, g: 14 }),
  E('salt', 1.29, '26 oz', { a: 'kosher salt|sea salt|table salt|fine salt|flaky salt|flaky sea salt|coarse salt|diamond crystal kosher salt|salt and pepper', c: 292 }),
  E('black pepper', 4.49, '3 oz', { a: 'pepper|ground black pepper|freshly ground black pepper|black peppercorn|peppercorn|cracked black pepper|ground pepper|white pepper', c: 110 }),
  E('cumin', 2.99, '1.5 oz', { a: 'ground cumin|cumin seed|whole cumin', c: 96 }),
  E('chili powder', 2.99, '2.5 oz', { a: 'ancho chili powder|chipotle chili powder|chile powder', c: 128 }),
  E('paprika', 2.99, '2 oz', { a: 'sweet paprika|hungarian paprika|ground paprika', c: 110 }),
  E('smoked paprika', 3.99, '1.75 oz', { a: 'spanish paprika|pimenton|hot paprika', c: 110 }),
  E('garlic powder', 2.99, '3 oz', { a: 'granulated garlic|garlic salt', c: 150 }),
  E('onion powder', 2.99, '2.6 oz', { a: 'granulated onion|dried minced onion|onion flake', c: 110 }),
  E('oregano', 2.49, '0.75 oz', { a: 'dried oregano|mexican oregano|oregano leaf', c: 48 }),
  E('dried basil', 2.49, '0.62 oz', { c: 30 }),
  E('thyme', 2.99, '0.75 oz', { a: 'dried thyme|thyme leaf|ground thyme', c: 48 }),
  E('dried rosemary', 2.99, '0.7 oz', { a: 'rosemary leaf', c: 53 }),
  E('dried parsley', 2.49, '0.4 oz', { a: 'parsley flake|dried dill|dill weed dried|dried chive|dried cilantro', c: 20 }),
  E('italian seasoning', 2.99, '0.87 oz', { a: 'herbs de provence|herbes de provence|dried italian herb|mixed herb|dried herb', c: 48 }),
  E('cinnamon', 2.99, '2.37 oz', { a: 'ground cinnamon|cinnamon stick', c: 125, sz: { stick: 3 } }),
  E('nutmeg', 3.99, '1.1 oz', { a: 'ground nutmeg|freshly grated nutmeg|whole nutmeg|allspice|ground allspice|mace', c: 110 }),
  E('ground ginger', 3.49, '0.8 oz', { a: 'dried ginger|powdered ginger', c: 90 }),
  E('turmeric', 3.49, '1 oz', { a: 'ground turmeric|turmeric powder', c: 150 }),
  E('curry powder', 3.49, '1.75 oz', { a: 'madras curry powder|yellow curry powder', c: 100 }),
  E('garam masala', 4.99, '2 oz', { a: 'tandoori masala|chaat masala|shawarma spice|shawarma spice blend|baharat|za atar|zaatar|ras el hanout|berbere|five spice|chinese five spice|jerk seasoning', c: 100 }),
  E('red pepper flake', 2.99, '1.5 oz', { a: 'crushed red pepper|chili flake|red chili flake|crushed red pepper flake|aleppo pepper|gochugaru', c: 90 }),
  E('cayenne', 2.99, '1.75 oz', { a: 'cayenne pepper|ground cayenne|ground red pepper', c: 90 }),
  E('bay leaf', 2.99, '0.12 oz', { a: 'bay leaves|dried bay leaf', g: 0.2, sz: { leaf: 0.2 } }),
  E('ground coriander', 3.49, '1.25 oz', { a: 'coriander|coriander seed|ground cardamom|cardamom|cardamom pod|fennel seed|mustard seed|caraway seed|dry mustard|mustard powder|celery seed|sumac|star anise', c: 80 }),
  E('ground cloves', 4.99, '0.9 oz', { a: 'ground clove|whole clove', c: 100 }),
  E('saffron', 7.99, '0.5 g', { a: 'saffron thread', c: 20, sz: { pinch: 0.05 } }),
  E('everything bagel seasoning', 3.99, '2.3 oz', { a: 'everything seasoning|everything but the bagel seasoning', c: 140 }),
  E('taco seasoning', 1.29, '1 oz', { a: 'taco seasoning mix|fajita seasoning|ranch seasoning|ranch dressing mix|onion soup mix|chili seasoning', c: 130, sz: { packet: 28, package: 28, envelope: 28 } }),
  E('cajun seasoning', 2.99, '2.5 oz', { a: 'creole seasoning|blackening seasoning|old bay|old bay seasoning|lemon pepper|lemon pepper seasoning|steak seasoning|poultry seasoning|seasoning salt|seasoned salt|adobo seasoning|bbq rub|dry rub|pumpkin pie spice|apple pie spice|seasoning', c: 120 }),
  E('nutritional yeast', 7.99, '5 oz', { a: 'nooch', c: 60 }),
  E('sesame seed', 2.99, '2 oz', { a: 'sesame seeds|toasted sesame seed|black sesame seed', c: 144 }),
  E('chia seed', 5.99, '12 oz', { a: 'chia seeds|flaxseed|ground flaxseed|flax seed|hemp seed|hemp heart', c: 170 }),

  /* ---------- Condiments & oils ---------- */
  E('olive oil', 8.99, '16.9 fl oz', { a: 'extra virgin olive oil|evoo|light olive oil|good olive oil', c: 216 }),
  E('vegetable oil', 3.99, '48 fl oz', { a: 'canola oil|neutral oil|cooking oil|oil|sunflower oil|grapeseed oil|peanut oil|corn oil|frying oil|safflower oil', c: 218 }),
  E('avocado oil', 7.99, '16.9 fl oz', { c: 218 }),
  E('sesame oil', 4.49, '5 fl oz', { a: 'toasted sesame oil|dark sesame oil|chili oil|chili crisp', c: 218 }),
  E('coconut oil', 5.99, '14 fl oz', { a: 'virgin coconut oil|refined coconut oil', c: 218 }),
  E('cooking spray', 3.49, '6 oz', { a: 'nonstick spray|nonstick cooking spray|olive oil spray|baking spray', c: 218 }),
  E('balsamic vinegar', 3.99, '16.9 fl oz', { a: 'balsamic|balsamic glaze|balsamic reduction', c: 255 }),
  E('red wine vinegar', 2.99, '16 fl oz', { a: 'sherry vinegar|champagne vinegar', c: 239 }),
  E('white wine vinegar', 2.99, '16 fl oz', { c: 239 }),
  E('apple cider vinegar', 2.99, '32 fl oz', { a: 'cider vinegar|acv', c: 239 }),
  E('rice vinegar', 2.99, '12 fl oz', { a: 'rice wine vinegar|seasoned rice vinegar|unseasoned rice vinegar', c: 239 }),
  E('white vinegar', 1.99, '32 fl oz', { a: 'distilled white vinegar|vinegar', c: 239 }),
  E('soy sauce', 2.99, '15 fl oz', { a: 'low sodium soy sauce|tamari|shoyu|light soy sauce|dark soy sauce|coconut aminos|liquid aminos', c: 255 }),
  E('fish sauce', 3.49, '7 fl oz', { c: 260 }),
  E('oyster sauce', 2.99, '9 oz', { c: 280 }),
  E('hoisin sauce', 2.99, '8.5 oz', { a: 'hoisin', c: 280 }),
  E('teriyaki sauce', 3.49, '10 fl oz', { a: 'teriyaki|teriyaki marinade', c: 260 }),
  E('sriracha', 3.99, '17 oz', { a: 'sriracha sauce|chili garlic sauce|sambal oelek|sambal', c: 260 }),
  E('hot sauce', 2.49, '6 fl oz', { a: 'tabasco|franks red hot|frank s red hot|buffalo sauce|louisiana hot sauce|cholula|valentina', c: 250 }),
  E('sweet chili sauce', 2.99, '10 fl oz', { a: 'thai sweet chili sauce', c: 300 }),
  E('worcestershire sauce', 2.99, '10 fl oz', { a: 'worcestershire|worchestershire sauce', c: 260 }),
  E('ketchup', 2.99, '32 oz', { a: 'tomato ketchup|catsup', c: 272 }),
  E('yellow mustard', 1.99, '14 oz', { a: 'mustard|prepared mustard|american mustard', c: 250 }),
  E('dijon mustard', 2.99, '8 oz', { a: 'dijon|whole grain mustard|grainy mustard|stone ground mustard|spicy brown mustard|honey mustard', c: 250 }),
  E('mayonnaise', 4.49, '30 fl oz', { a: 'mayo|light mayonnaise|vegan mayo|kewpie mayo|aioli', c: 220 }),
  E('bbq sauce', 2.49, '18 oz', { a: 'barbecue sauce|barbeque sauce', c: 290 }),
  E('ranch dressing', 3.49, '16 fl oz', { a: 'ranch|blue cheese dressing', c: 240 }),
  E('salad dressing', 2.99, '16 fl oz', { a: 'italian dressing|vinaigrette|caesar dressing|balsamic vinaigrette|greek dressing|poppyseed dressing|honey mustard dressing|dressing', c: 240 }),
  E('honey', 5.99, '12 oz', { a: 'raw honey|local honey|hot honey', c: 340 }),
  E('maple syrup', 8.99, '12.5 fl oz', { a: 'pure maple syrup', c: 315 }),
  E('pancake syrup', 3.49, '24 fl oz', { a: 'syrup|table syrup|agave|agave nectar|corn syrup|light corn syrup|simple syrup', c: 315 }),
  E('gochujang', 5.99, '17.6 oz', { a: 'korean chili paste|doenjang', c: 300 }),
  E('miso', 5.99, '14 oz', { a: 'white miso|miso paste|red miso|yellow miso|shiro miso', c: 275 }),
  E('tahini', 6.99, '16 oz', { a: 'sesame paste', c: 240 }),
  E('hummus', 3.99, '10 oz', { a: 'classic hummus|roasted red pepper hummus', c: 246 }),
  E('curry paste', 3.49, '4 oz', { a: 'red curry paste|green curry paste|thai curry paste|yellow curry paste|massaman curry paste|harissa|tomato chutney|mango chutney', c: 250 }),
  E('lemon juice', 2.99, '15 fl oz', { a: 'fresh lemon juice|bottled lemon juice', c: 244 }),
  E('lime juice', 2.99, '15 fl oz', { a: 'fresh lime juice|key lime juice', c: 244 }),
  E('mirin', 3.99, '10 fl oz', { a: 'rice wine|shaoxing wine|sake|cooking sherry|dry sherry|sherry|marsala|marsala wine|cooking wine', c: 240 }),

  /* ---------- Beverages ---------- */
  E('coffee', 9.99, '12 oz', { a: 'ground coffee|coffee bean|espresso|instant coffee|espresso powder|brewed coffee|cold brew', c: 85 }),
  E('tea', 3.49, '20 each', { a: 'tea bag|black tea|green tea|herbal tea|chai|matcha', g: 2 }),
  E('orange juice', 3.99, '52 fl oz', { a: 'oj|fresh orange juice|pulp free orange juice', c: 248 }),
  E('apple juice', 2.99, '64 fl oz', { a: 'apple cider|cranberry juice|grape juice|juice|pineapple juice', c: 248 }),
  E('sparkling water', 4.99, '96 fl oz', { a: 'seltzer|club soda|soda water|mineral water|la croix|tonic water', c: 237 }),
  E('soda', 7.49, '144 fl oz', { a: 'cola|coke|pop|ginger ale|diet soda|soft drink|sprite', c: 245 }),
  E('white wine', 9.99, '750 ml', { a: 'dry white wine|wine|sauvignon blanc|pinot grigio|chardonnay|prosecco|champagne|rose', c: 236 }),
  E('red wine', 9.99, '750 ml', { a: 'dry red wine|cabernet|merlot|pinot noir|red wine for cooking', c: 236 }),
  E('beer', 10.99, '72 fl oz', { a: 'lager|ale|stout|ipa|pale ale|dark beer|guinness', c: 237 }),
  E('water', 0, 'gallon', { a: 'cold water|warm water|hot water|boiling water|ice water|ice|ice cube|tap water|filtered water', c: 237 }),

  /* ---------- Snacks & nuts ---------- */
  E('almond', 6.99, 'lb', { a: 'almonds|sliced almond|slivered almond|toasted almond|raw almond|marcona almond', g: 1.2, c: 143 }),
  E('walnut', 7.99, 'lb', { a: 'walnuts|walnut half|chopped walnut', c: 117 }),
  E('pecan', 9.99, 'lb', { a: 'pecans|pecan half|chopped pecan', c: 109 }),
  E('cashew', 8.99, 'lb', { a: 'cashews|raw cashew|roasted cashew|pistachio|macadamia|macadamia nut|hazelnut|mixed nut|nuts', c: 137 }),
  E('peanut', 3.99, '16 oz', { a: 'peanuts|roasted peanut|dry roasted peanut|crushed peanut', c: 146 }),
  E('pine nut', 7.99, '4 oz', { a: 'pine nuts|pignoli', c: 135 }),
  E('pumpkin seed', 4.99, '8 oz', { a: 'pepita|pepitas|sunflower seed|sunflower seeds|pumpkin seeds', c: 129 }),
  E('raisin', 3.49, '12 oz', { a: 'raisins|golden raisin|currant|dried apricot|dried fruit|dried cherry|prune', c: 145 }),
  E('dried cranberry', 3.49, '6 oz', { a: 'craisin|dried cranberries|sweetened dried cranberry', c: 120 }),
  E('shredded coconut', 2.99, '7 oz', { a: 'coconut|coconut flake|unsweetened shredded coconut|sweetened coconut|desiccated coconut|toasted coconut', c: 93 }),
  E('tortilla chip', 3.99, '13 oz', { a: 'tortilla chips|corn chip|chips|nacho chip|pita chip', c: 28 }),
  E('potato chip', 4.49, '8 oz', { a: 'potato chips|kettle chip|crisps', c: 20 }),
  E('cracker', 3.49, '9 oz', { a: 'crackers|saltine|saltines|ritz|club cracker|water cracker|butter cracker|rice cracker|oyster cracker', g: 3, c: 60 }),
  E('pretzel', 2.99, '16 oz', { a: 'pretzels|pretzel stick|pretzel twist', c: 60 }),
  E('popcorn', 2.99, '30 oz', { a: 'popcorn kernel|popped popcorn|microwave popcorn', c: 8 }),
  E('granola', 4.49, '12 oz', { a: 'granola cluster', c: 110 }),
  E('granola bar', 3.99, '6 each', { a: 'protein bar|cereal bar', g: 40 }),
  E('cereal', 3.99, '12 oz', { a: 'breakfast cereal|corn flake|cornflakes|rice krispies|cheerios|bran flake', c: 30 }),
  E('pancake mix', 2.99, '32 oz', { a: 'bisquick|baking mix|waffle mix|biscuit mix|cake mix|brownie mix|muffin mix|cornbread mix', c: 120 }),

  /* ---------- Household ---------- */
  E('paper towel', 2.49, 'each', { a: 'paper towels|kitchen roll', x: 1 }),
  E('aluminum foil', 4.99, 'each', { a: 'foil|tin foil|heavy duty foil', x: 1 }),
  E('plastic wrap', 3.49, 'each', { a: 'cling wrap|saran wrap|cling film', x: 1 }),
  E('parchment paper', 4.49, 'each', { a: 'parchment|baking paper|wax paper', x: 1 }),
  E('zip top bag', 3.99, 'box', { a: 'ziploc|ziploc bag|zip bag|freezer bag|sandwich bag|storage bag', x: 1 }),
  E('dish soap', 3.49, 'bottle', { a: 'dishwashing liquid|dawn|dishwasher detergent|dishwasher pod', x: 1 }),
  E('trash bag', 9.99, 'box', { a: 'garbage bag|trash bags|bin liner', x: 1 }),
  E('napkin', 3.49, 'package', { a: 'napkins|paper napkin|paper plate|paper plates|paper cup', x: 1 }),
  E('sponge', 3.49, 'package', { a: 'sponges|scrub sponge', x: 1 }),
  E('toilet paper', 8.99, 'package', { a: 'tp|bath tissue|tissue|tissues|facial tissue', x: 1 }),
  E('laundry detergent', 12.99, 'bottle', { a: 'detergent|laundry pod|fabric softener', x: 1 }),
];

export const ESTIMATE_COUNT = PRICE_DB.length;
